### ISSUE TITLE
kasada browser fingerprint

### ISSUE THREAD

**Issue by j501809412** [0x6a69616e/kpsdk-solver#14]
Hello, thank you for your open source kasada solver project which helped me a lot. I downloaded the project and ran it for two consecutive days to generate x-kpsdk-cd and x-kpsdk-ct. But just now I found that when the generated x-kpsdk-cd and x-kpsdk-ct parameters were submitted to the website api, Kasda blocked the request and returned status code 429.

Is it because I have been running the project that Kasada has blocked the fingerprint of the Playwright browser?
I wonder if you have encountered similar problems?

**Comment by j501809412** [comment]
> Repeatedly opening and closing the solver instance (loading the SDK script and configuring the solver each time) may lead to potential issues. After a certain period of this activity, you may temporarily hit a ratelimit, causing Kasada's fingerprinting `/fp` endpoint to respond with a status 429 and no response body. As a workaround, you can [assign proxies for each BrowserContext that is created](https://playwright.dev/docs/api/class-browser#browser-new-context-option-proxy).
> 
> Let me know if this helps!

Hello, I have tried adding a proxy to run. The final result is the same as returning status code 429. The request is blocked.

**Comment by j501809412** [comment]
> May I know what's your target service and the modified code involved?

Okay, can you send me your email address? I will send you the code via email

**Comment by 0x6a69616e** [comment]
> > May I know what's your target service and the modified code involved?
> 
> Okay, can you send me your email address? I will send you the code via email

0x6a69616e@gmail.com

**Comment by j501809412** [comment]
> > > May I know what's your target service and the modified code involved?
> > 
> > 
> > Okay, can you send me your email address? I will send you the code via email
> 
> [0x6a69616e@gmail.com](mailto:0x6a69616e@gmail.com)

Hello, the code has been sent. Please check your email.

**Comment by j501809412** [comment]
> > > May I know what's your target service and the modified code involved?
> > 
> > 
> > Okay, can you send me your email address? I will send you the code via email
> 
> [0x6a69616e@gmail.com](mailto:0x6a69616e@gmail.com)

The email failed to be sent just now, so I sent it again.
