### ISSUE TITLE
browser not open again

### ISSUE THREAD

**Issue by berdoff** [0x6a69616e/kpsdk-solver#15]
node:internal/process/promises:289
            triggerUncaughtException(err, true /* fromPromise */);
            ^

page.evaluate: Target page, context or browser has been closed

I have placed the code from test.js is in a loop, but when you reopen the browser, it does not open if the previous one was closed via close()

**Comment by berdoff** [comment]
solve

**Comment by berdoff** [comment]
add use proxy pls

**Comment by berdoff** [comment]
solve

**Comment by berdoff** [comment]
1

**Comment by 0x6a69616e** [comment]
???
