### ISSUE TITLE
Are you interested in collaborating

### ISSUE THREAD

**Issue by LeftMonster** [0x6a69616e/kpsdk-solver#16]
Are you interested in studying their risk control system(Web API WAF)?

I can share the generation algorithm I have here, as well as the trained model to bypass their risk control system.

For instance: ips.js, tl, fingerprint.

tl request body data

**Comment by 0x6a69616e** [comment]
Yes, I am interested in studying Kasada's risk control system. Could we communicate via Discord or Telegram to discuss this further?

Telegram: https://t.me/e61696a6x0
Discord: @**0x6a69616e**

Thanks!
