### ISSUE TITLE
Question Regarding Deobfuscation  kpsdk-solver

### ISSUE THREAD

**Issue by Kingkross1** [0x6a69616e/kpsdk-solver#4]
Hello,

I recently came across your repository while learning about reverse engineering. First, I want to thank you for making this open-source resource available; it's been incredibly insightful for a beginner like myself.

However, I'm encountering some challenges with deobfuscation, particularly concerning the modifications made to the original p.js file. For instance, functions like KPSDK_0x8410 and others appear to have been removed in p_deobf.js . I'm especially curious about how you managed to deobfuscate the intricate parts of the code, such as the variables _0x586c98 = KPSDK_0x2e2f, _0x26c6c1.

Any guidance or tips you could provide on your approach to deobfuscating such complex code would be greatly appreciated.

Additionally, if you have a Discord channel or a Telegram group for reverse engineering enthusiasts, I would be eager to join and learn more from the community.

Thank you once again for your contributions to the open-source community. I apologize if this isn't the appropriate channel for such queries; I'm still quite new to this.

Best regards,

**Comment by 0x6a69616e** [comment]
I generated `p_deobf.js` with the help of [obf-io.deobfuscate.io](https://obf-io.deobfuscate.io). This online tool is designed specifically for scripts that have been obfuscated by [obfuscator.io](https://obfuscator.io), and I find it to be pretty effective.

Unfortunately, I do not have a Discord or Telegram community relevant to reverse-engineering. However, if you have any further questions regarding kpsdk-solver, please feel free to reach out to me on Discord @**0x6a69616e**.

Thanks!
