### ISSUE TITLE
Twitch Integrity Token

### ISSUE THREAD

**Issue by maximen39** [0x6a69616e/kpsdk-solver#8]
Hi! I need to get integrity tokens for twitch auth tokens. But now, as I understand it, there are problems in this. I'd like to help u.
And I would like to get in touch for further development

**Comment by 0x6a69616e** [comment]
Hey @maximen39, that would be very much appreciated! I assume you have prior experience with Puppeteer/Playwright or reverse-engineering?

I've already been working on an iteration based on my concept as discussed in [#6 (comment)](https://github.com/0x6a69616e/kpsdk-solver/issues/6#issuecomment-1931161571), but I could maybe use your help with issues I'm struggling to solve. My progress will be on a separate branch for us to collaborate on.

Let's get in touch on Discord @**0x6a69616e**.
